name = "Rewrite"
uuid = "329df15e-4b1e-11e8-0b4f-55ede0b53481"
authors = ["Harrison Grodin <harrison.grodin@gmail.com>, Yijia Chen <yijiachenmain@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
SpecialSets = "c6b63f46-9023-11e8-3b28-1f7d8c94880d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
